services:

  auth_service:
    build: ./auth_service
    ports:
      - "8001:8000"

  transaction_service:
    build: ./transaction_service
    ports:
      - "8002:8000"

  face_verification_service:
    build: ./face_verification_service
    ports:
      - "8003:8000"
