volumes:
  photo_storage:

services:

  zookeeper:
        image: bitnami/zookeeper:latest
        ports:
            - 2181:2181
        environment:
            - ALLOW_ANONYMOUS_LOGIN=yes

  kafka:
    image: bitnami/kafka:latest
    ports:
      - 9092:9092
      - 9093:9093
    environment:
       - KAFKA_BROKER_ID=1
       - KAFKA_CFG_LISTENERS=PLAINTEXT://:9092
       - KAFKA_CFG_ADVERTISED_LISTENERS=PLAINTEXT://127.0.0.1:9092
       - KAFKA_CFG_ZOOKEEPER_CONNECT=zookeeper:2181
       - ALLOW_PLAINTEXT_LISTENER=yes
       - KAFKA_CFG_LISTENER_SECURITY_PROTOCOL_MAP=CLIENT:PLAINTEXT
       - KAFKA_CFG_LISTENERS=CLIENT://:9092
       - KAFKA_CFG_ADVERTISED_LISTENERS=CLIENT://kafka:9092
       - KAFKA_CFG_INTER_BROKER_LISTENER_NAME=CLIENT
       - KAFKA_CREATE_TOPICS= "faces:3:1"
    depends_on:
       - zookeeper

  auth_service:
    build: ./auth_service
    depends_on:
      - kafka
      - zookeeper
    volumes:
      - photo_storage:/app/photos

  transaction_service:
    build: ./transaction_service
    depends_on:
      - kafka
      - zookeeper

  face_verification_service:
    build: ./face_verification_service
    depends_on:
      - kafka
      - zookeeper
    volumes:
      - photo_storage:/app/photos

  api_gateway:
    build: .
    ports:
      - "8000:8000"
    depends_on:
      - auth_service
      - transaction_service
      - face_verification_service
      - kafka
      - zookeeper
