service:
  title: "API Gateway"
  description: "Единая точка входа в несколько сервисов."
  host: "0.0.0.0"
  port: 8000
  debug: True

auth_service:
  base_url: "http://auth_service/api/"
  tags_metadata:
    name: "Auth service"
    description: "Сервис авторизации"

transaction_service:
  base_url: "http://transaction_service/api/"
  tags_metadata:
    name: "Transaction service"
    description: "Сервис транзакций"

face_verification:
  base_url: "http://face_verification_service/api/"
  tags_metadata:
    name: "Face verification service"
    description: "Сервис верификации"
