service:
  title: "API Gateway"
  description: "Entrance point for services."
  host: "0.0.0.0"
  port: 8000
  debug: True
  tags_metadata_health:
    name: "Health"
    description: "Service health check"

auth_service:
  base_url: "http://auth_service:8000/api"
  tags_metadata:
    name: "Auth service"
    description: "Authentication service"

transaction_service:
  base_url: "http://transaction_service:8000/api"
  tags_metadata:
    name: "Transaction service"
    description: "Transaction service"

jaeger:
  service_name: "gateway"
  host: "jaeger"
  port: 6831
  logging: True
  sampler_type: "const"
  sampler_param: 1
