service:
  title: "API Gateway"
  description: "Единая точка входа в несколько сервисов."
  host: "0.0.0.0"
  port: 8000
  debug: True
  tags_metadata_health:
    name: "Health"
    description: "Проверка доступности сервиса"

auth_service:
  base_url: "http://localhost:8001/api"
  tags_metadata:
    name: "Auth service"
    description: "Сервис авторизации"

transaction_service:
  base_url: "http://localhost:8002/api"
  tags_metadata:
    name: "Transaction service"
    description: "Сервис транзакций"

jaeger:
  service_name: "gateway"
  host: "localhost"
  port: 6831
  logging: True
  sampler_type: "const"
  sampler_param: 1
