apiVersion: v1
kind: ConfigMap
metadata:
  name: stakrotckii-api-gateway-configmap
data:
  config.yaml: |
    service:
      title: "API Gateway"
      description: "Entrance point for services."
      host: "0.0.0.0"
      port: 8000
      debug: True
      tags_metadata_health:
        name: "Health"
        description: "Service health check"
    auth_service:
      base_url: "http://stakrotckii-auth-service-service:8000/api/"
      tags_metadata:
         name: "Auth service"
         description: "Authentication service"

    transaction_service:
      base_url: "http://stakrotckii-transaction-service-service:8000/api/"
      tags_metadata:
        name: "Transaction service"
        description: "Transaction service"

    jaeger:
      service_name: "stakrotckii_gateway"
      host: "jaeger-query-service"
      port: 6831
      logging: True
      sampler_type: "const"
      sampler_param: 1
